#!/bin/sh
#
# Copyright (C) u-blox
#
# u-blox reserves all rights in this deliverable (documentation, software, etc.,
# hereafter "Deliverable").
#
# u-blox grants you the right to use, copy, modify and distribute the Deliverable
# provided hereunder for any purpose without fee, provided this entire notice is
# included in all copies of any software which is or includes a copy or
# modification of this software and in all copies of the supporting documentation
# for such software.
#
# THIS DELIVERABLE IS BEING PROVIDED "AS IS", WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY. IN PARTICULAR, NEITHER THE AUTHOR NOR U-BLOX MAKES ANY REPRESENTATION
# OR WARRANTY OF ANY KIND CONCERNING THE MERCHANTABILITY OF THIS DELIVERABLE OR
# ITS FITNESS FOR ANY PARTICULAR PURPOSE.
#
# In case you provide us a feedback or make a contribution in the form of a
# further development of the Deliverable ("Contribution"), u-blox will have the
# same rights as granted to you, namely to use, copy, modify and distribute the
# Contribution provided to us for any purpose without fee.
#

#
# LILY-W1 mfgbridge init script
#

DAEMON=/opt/lily-w1/mfg-tools/mfgbridge
PIDFILE=/var/run/mfgbridge.pid
DESC="LILY-W1 mfgbridge"
RET=1

LILY_SDIO=sd8801_mfg
LILY_USB=usb8801_mfg

test -x $DAEMON || exit 1

do_start() {
    local driver_to_use=$1

    if [ _$driver_to_use == _$LILY_SDIO ]; then
        modprobe -q omap_hsmmc
    fi
    modprobe -q $driver_to_use

    cd $(dirname $DAEMON) || return $?
    start-stop-daemon -S -o -q -m -p $PIDFILE -x ./$(basename $DAEMON) \
        -- -B
}

do_stop() {
    local driver_to_use=$1

    start-stop-daemon -K -o -q -p $PIDFILE
    rm -f $PIDFILE
    if [ _$driver_to_use == _$LILY_SDIO ]; then
        modprobe -q -r omap_hsmmc
    fi
    modprobe -q -r $driver_to_use
}

case "$1" in
    start|start-sdio)
        echo -n "Starting ${DESC} (SDIO): "
        do_start $LILY_SDIO
        RET=$?
        ;;
    start-usb)
        echo -n "Starting ${DESC} (USB): "
        do_start $LILY_USB
        RET=$?
        ;;
    stop|stop-sdio)
        echo -n "Stopping ${DESC} (SDIO): "
        do_stop $LILY_SDIO
        RET=$?
        ;;
    stop-usb)
        echo -n "Stopping ${DESC} (USB): "
        do_stop $LILY_USB
        RET=$?
        ;;
    restart|restart-sdio)
        echo -n "Restarting ${DESC} (SDIO): "
        do_stop $LILY_SDIO
        do_start $LILY_SDIO
        RET=$?
        ;;
    restart-usb)
        echo -n "Restarting ${DESC} (USB): "
        do_stop $LILY_USB
        do_start $LILY_USB
        RET=$?
        ;;
    *)
        echo "Usage: $0 {start[-sdio/-usb]|stop[-sdio/-usb]|restart[-sdio/-usb]}"
        exit 1
esac

if [ $RET -eq 0 ]; then
    echo "$(basename $DAEMON)"
else
    echo failed
fi

exit $RET
